<?php

class Caselaw{

	//setting the private variables
	private $caselaw_id;
	private $sec_num;
	private $case_id;
	private $court_id;
	private $user_id;
	private $case_date;
	private $url;
	private $case_ref;
	private $case_desc;

	//constructor used to create new objects
	public function __construct($caselaw_id, $sec_num, $case_id, $court_id, $user_id, $case_date, $url, $case_ref, $case_desc)
		{
			$this->caselaw_id = $caselaw_id;
			$this->sec_num = $sec_num;
			$this->case_id = $case_id;
			$this->court_id = $court_id;
			$this->user_id = $user_id;
			$this->case_date = $case_date;
			$this->url = $url;
			$this->case_ref = $case_ref;
			$this->case_desc = $case_desc;
		}


	//Autogenerated getters and setters

    /**
     * Gets the value of caselaw_id.
     *
     * @return mixed
     */
    public function getCaselaw_id()
    {
        return $this->caselaw_id;
    }

    /**
     * Sets the value of caselaw_id.
     *
     * @param mixed $caselaw_id the caselaw_id
     *
     * @return self
     */
    public function setCaselaw_id($caselaw_id)
    {
        $this->caselaw_id = $caselaw_id;

        return $this;
    }

    /**
     * Gets the value of sec_num.
     *
     * @return mixed
     */
    public function getSec_num()
    {
        return $this->sec_num;
    }

    /**
     * Sets the value of sec_num.
     *
     * @param mixed $sec_num the sec_num
     *
     * @return self
     */
    public function setSec_num($sec_num)
    {
        $this->sec_num = $sec_num;

        return $this;
    }

    /**
     * Gets the value of case_id.
     *
     * @return mixed
     */
    public function getCase_id()
    {
        return $this->case_id;
    }

    /**
     * Sets the value of case_id.
     *
     * @param mixed $case_id the case_id
     *
     * @return self
     */
    public function setCase_id($case_id)
    {
        $this->case_id = $case_id;

        return $this;
    }

    /**
     * Gets the value of court_id.
     *
     * @return mixed
     */
    public function getCourt_id()
    {
        return $this->court_id;
    }

    /**
     * Sets the value of court_id.
     *
     * @param mixed $court_id the court_id
     *
     * @return self
     */
    public function setCourt_id($court_id)
    {
        $this->court_id = $court_id;

        return $this;
    }

    /**
     * Gets the value of user_id.
     *
     * @return mixed
     */
    public function getUser_id()
    {
        return $this->user_id;
    }

    /**
     * Sets the value of user_id.
     *
     * @param mixed $user_id the user_id
     *
     * @return self
     */
    public function setUser_id($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Gets the value of case_date.
     *
     * @return mixed
     */
    public function getCase_date()
    {
        return $this->case_date;
    }

    /**
     * Sets the value of case_date.
     *
     * @param mixed $case_date the case_date
     *
     * @return self
     */
    public function setCase_date($case_date)
    {
        $this->case_date = $case_date;

        return $this;
    }

    /**
     * Gets the value of url.
     *
     * @return mixed
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Sets the value of url.
     *
     * @param mixed $url the url
     *
     * @return self
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Gets the value of case_ref.
     *
     * @return mixed
     */
    public function getCase_ref()
    {
        return $this->case_ref;
    }

    /**
     * Sets the value of case_ref.
     *
     * @param mixed $case_ref the case_ref
     *
     * @return self
     */
    public function setCase_ref($case_ref)
    {
        $this->case_ref = $case_ref;

        return $this;
    }

    /**
     * Gets the value of case_desc.
     *
     * @return mixed
     */
    public function getCase_desc()
    {
        return $this->case_desc;
    }

    /**
     * Sets the value of case_desc.
     *
     * @param mixed $case_desc the case_desc
     *
     * @return self
     */
    public function setCase_desc($case_desc)
    {
        $this->case_desc = $case_desc;

        return $this;
    }
}

?>